//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace MailMergeKit.WordAddin
{
    partial class ThisAddIn
    {
        private System.ComponentModel.IContainer components = null;

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
        }
    }
}
#pragma warning restore 414

