//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace MailMergeKit.WordAddin
{
    partial class ThisAddIn
    {
        internal void InternalStartup()
        {
        }
    }
}
#pragma warning restore 414

